name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        include:
        - platform: ['self-hosted', 'linux', 'ARM64']
          dockerfile: packaged/Dockerfile.arm64v8
          tag: v1.2.5

        - platform: ['self-hosted', 'linux', 'ARM']
          dockerfile: packaged/Dockerfile.arm32v7
          tag: v1.2.5

        - platform: ['self-hosted', 'Linux', 'X64']
          dockerfile: packaged/Dockerfile.amd64
          tag: v1.2.5

#         - platform: ['self-hosted', 'linux', 'ARM64']
#           dockerfile: fromsource/Dockerfile.arm64v8
#           tag: v1.2.5

#         - platform: ['self-hosted', 'linux', 'ARM32']
#           dockerfile: fromsource/Dockerfile.arm32v7
#           tag: v1.2.5

#         - platform: ['self-hosted', 'linux', 'X86']
#           dockerfile: fromsource/Dockerfile.amd64
#           tag: v1.2.5

    name: Build ${{ matrix.platform }} ${{ matrix.dockerfile }}
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Container ${{ matrix.platform }}
        env:
          NECKLESS_PRIVKEY: ${{ secrets.NECKLESS_PRIVKEY }}
        run: |
          GITVER=$(git rev-parse --short HEAD)
          ARCH=$(echo ${{ matrix.dockerfile}} | sed 's/.*\.\([^\.][^\.]*\)$/\1/')
          TAG=fastandfearless/tailscale:$(dirname ${{ matrix.dockerfile}})-${ARCH}-${{ matrix.tag }}-${GITVER}
          docker build --build-arg TAG=${{ matrix.tag }} -t $TAG -f ${{ matrix.dockerfile}} .
          neckless kv ls --onlyValue DOCKER_PASSWORD | \
            docker login docker.io -u $(neckless kv ls --onlyValue DOCKER_USER) --password-stdin
          docker tag docker.io/$TAG $TAG
          docker push docker.io/$TAG

